/**
 * Route names and parameter types for type-safe navigation.
 * All screen routes defined here — never use raw strings in navigation calls.
 */
export const Routes = {
  AUTH: {
    SPLASH: '/',
    ONBOARDING: '/onboarding',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    OTP_VERIFY: '/auth/otp-verify',
  },
  CUSTOMER: {
    HOME: '/customer/home',
    SEARCH: '/customer/search',
    CATEGORY: '/customer/category/[id]',
    SUBCATEGORY: '/customer/subcategory/[id]',
    BOOKING_FORM: '/customer/booking/form',
    CHECKOUT: '/customer/booking/checkout',
    BOOKING_CONFIRM: '/customer/booking/confirm',
    BOOKING_TRACKER: '/customer/booking/[id]/tracker',
    BOOKING_HISTORY: '/customer/bookings',
    BOOKING_DETAIL: '/customer/booking/[id]',
    CHAT: '/customer/chat/[bookingId]',
    RATE_REVIEW: '/customer/booking/[id]/review',
    WALLET: '/customer/wallet',
    PROFILE: '/customer/profile',
    SETTINGS: '/customer/settings',
    NOTIFICATIONS: '/customer/notifications',
    PROVIDER_PROFILE: '/customer/provider/[id]',
    RECURRING_BOOKINGS: '/customer/recurring',
    RECURRING_SETUP: '/customer/recurring/setup',
    RECURRING_DETAIL: '/customer/recurring/[id]',
    BUSINESS_ACCOUNTS: '/customer/business',
    BUSINESS_DETAIL: '/customer/business/[id]',
    BUSINESS_CREATE: '/customer/business/create',
    BUSINESS_MEMBERS: '/customer/business/[id]/members',
    BUSINESS_CONTRACTS: '/customer/business/[id]/contracts',
    BUSINESS_INVOICES: '/customer/business/[id]/invoices',
    BUSINESS_INVOICE_DETAIL: '/customer/business/[id]/invoices/[invoiceId]',
    SERVICE_AREAS: '/customer/service-areas',
    SERVICE_AREA_DETAIL: '/customer/service-areas/[slug]',
    WAITLIST: '/customer/service-areas/waitlist',
    REBOOKING: '/customer/booking/[id]/rebook',
    SLOT_WAITLIST: '/customer/slot-waitlist',
    DATA_PRIVACY: '/customer/data-privacy',
    DATA_EXPORT: '/customer/data-export',
    ACCOUNT_DELETION: '/customer/account-deletion',
    SECURITY_SETTINGS: '/customer/security',
    DEVICE_MANAGEMENT: '/customer/security/devices',
    ACCESSIBILITY_SETTINGS: '/customer/settings/accessibility',
  },
  PROVIDER: {
    HOME: '/provider/home',
    JOB_DETAIL: '/provider/job/[id]',
    QUOTE_BUILDER: '/provider/job/[id]/quote',
    ACTIVE_JOB: '/provider/job/[id]/active',
    WALLET: '/provider/wallet',
    EARNINGS: '/provider/earnings',
    EARNINGS_GOALS: '/provider/earnings/goals',
    DEMAND_INSIGHTS: '/provider/demand-insights',
    MONTHLY_SUMMARY: '/provider/monthly-summary',
    RECEIPT: '/provider/receipt/[bookingId]',
    MATERIALS_LIST: '/provider/job/[id]/materials',
    SCHEDULE: '/provider/schedule',
    PROFILE: '/provider/profile',
    SETTINGS: '/provider/settings',
    REVIEWS: '/provider/reviews',
    SERVICE_AREAS: '/provider/service-areas',
  },
} as const;
