/**
 * Centralized icon module for the mobile app.
 *
 * Re-exports from `lucide-react-native`. Same contract as the admin module:
 * never import directly from `lucide-react-native` elsewhere — always go
 * through this file.
 *
 * See docs/design-system/icon-catalog.md for the canonical mapping.
 */

export {
  Sparkles,
  Wrench,
  Zap,
  ShowerHead,
  Paintbrush2,
  Home,
  Hammer,
  Bell,
  BellOff,
  User,
  UserCheck,
  Users,
  ClipboardList,
  Calendar,
  Clock,
  MapPin,
  Map as MapIcon,
  Navigation,
  Phone,
  Mail,
  MessageSquare,
  Star,
  Heart,
  Camera,
  Image as ImageIcon,
  Upload,
  Download,
  Eye,
  EyeOff,
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  Search,
  Filter,
  Plus,
  Minus,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  Coins,
  Banknote,
  CreditCard,
  Wallet,
  Receipt,
  Tag,
  Settings,
  HelpCircle,
  LogOut,
  Lock,
  Shield,
  Repeat,
  RefreshCw,
} from 'lucide-react-native';
