import React from 'react';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import * as ImagePicker from 'expo-image-picker';
import { captureImageAsync } from '@/utils/image-capture';
import { uploadImages } from '@/services/upload.service';
import { useOnboardingStore } from '@/stores/onboarding.store';
import { applicantId, completeApplicationFields, deferred, mockDraftSaves, readyApplication } from '../test-support/application-draft-fixture';
import Documents from '../app/provider-onboarding/documents';
import Selfie from '../app/provider-onboarding/selfie';

const mockPush = jest.fn();
jest.mock('expo-router', () => ({ useRouter: () => ({ push: mockPush, back: jest.fn() }) }));
jest.mock('expo-image-picker', () => ({ requestMediaLibraryPermissionsAsync: jest.fn(), launchImageLibraryAsync: jest.fn() }));
jest.mock('@/utils/image-capture', () => ({ captureImageAsync: jest.fn(), isCameraCaptureAvailable: () => false }));
jest.mock('@/services/upload.service', () => ({ uploadImages: jest.fn() }));

it('Bug UX-1323 — document and selfie operations remain bound to the applicant from permission through picker and upload', async () => {
  readyApplication();
  let view = render(<Documents />);
  const permission = deferred<Awaited<ReturnType<typeof ImagePicker.requestMediaLibraryPermissionsAsync>>>();
  jest.mocked(ImagePicker.requestMediaLibraryPermissionsAsync).mockReturnValueOnce(permission.promise);
  fireEvent.click(screen.getByRole('button', { name: /Government ID — Front/ }));
  await act(async () => readyApplication());
  await act(async () => permission.resolve({ status: 'granted' } as never));
  expect(ImagePicker.launchImageLibraryAsync).not.toHaveBeenCalled();
  view.unmount();
  readyApplication();
  view = render(<Documents />);
  jest.mocked(ImagePicker.requestMediaLibraryPermissionsAsync).mockResolvedValue({ status: 'granted' } as never);
  const picked = deferred<ImagePicker.ImagePickerResult>();
  jest.mocked(ImagePicker.launchImageLibraryAsync).mockReturnValueOnce(picked.promise);
  fireEvent.click(screen.getByRole('button', { name: /Government ID — Front/ }));
  await waitFor(() => expect(ImagePicker.launchImageLibraryAsync).toHaveBeenCalledTimes(1));
  await act(async () => readyApplication());
  await act(async () => picked.resolve({ canceled: false, assets: [{ uri: 'blob:old-applicant' }] } as never));
  expect(uploadImages).not.toHaveBeenCalled();
  view.unmount();
  readyApplication(completeApplicationFields());
  view = render(<Selfie />);
  jest.mocked(captureImageAsync).mockResolvedValue({ status: 'done', result: { canceled: false, assets: [{ uri: 'blob:old-selfie' }] } } as never);
  const uploaded = deferred<Awaited<ReturnType<typeof uploadImages>>>();
  jest.mocked(uploadImages).mockReturnValueOnce(uploaded.promise);
  fireEvent.click(screen.getByRole('button', { name: 'Replace Selfie' }));
  await waitFor(() => expect(uploadImages).toHaveBeenCalledTimes(1));
  await act(async () => readyApplication());
  await act(async () => uploaded.resolve([{ url: `onboarding/${applicantId}/late.jpg` }] as never));
  expect(useOnboardingStore.getState().selfieUri).toBeNull();
  expect(mockPush).not.toHaveBeenCalled();
  view.unmount();
  // The same guards must still allow the current applicant to upload and save.
  readyApplication(completeApplicationFields());
  mockDraftSaves();
  view = render(<Documents />);
  jest.mocked(ImagePicker.launchImageLibraryAsync).mockResolvedValue({ canceled: false, assets: [{ uri: 'blob:current-front' }] } as never);
  jest.mocked(uploadImages).mockResolvedValue([{ url: `onboarding/${applicantId}/current-front.jpg` }] as never);
  fireEvent.click(screen.getByRole('button', { name: /Government ID — Front/ }));
  await waitFor(() => expect(useOnboardingStore.getState().governmentIdFrontUri).toBe(`onboarding/${applicantId}/current-front.jpg`));
  fireEvent.click(screen.getByRole('button', { name: 'Save & continue' }));
  await waitFor(() => expect(mockPush).toHaveBeenCalledWith('/provider-onboarding/selfie'));
  view.unmount();
});
